### PR TITLE
v2.2.1 release: backports tx v2.1.1 for Istanbul support

### PR DESCRIPTION
**Pull request by s1na**
See #74 for discussion

### CODE REVIEW

**Comment by s1na** [comment]
So I updated `ethereumjs-tx` to `v2.1.1` on top of the `v2.2.0` tag. Also bumped the version and added a changelog entry. It should be ready for publishing if you all think it looks good.

**Comment by holgerd77** [comment]
For releasing this, I would checkout the respective merge commit and release from there, is this correct (after merging here if course)?

Also tests are failing due to this xvfb thing, can this be corrected?

**Comment by holgerd77** [comment]
Also: did you have another PR for review today? Wonder if I accidentally deleted some notification.

**Comment by s1na** [comment]
> For releasing this, I would checkout the respective merge commit and release from there, is this correct (after merging here if course)?

Don't merge please, we don't want these changes in master. You could checkout to this branch, build and release directly from there normally.

> Also tests are failing due to this xvfb thing, can this be corrected?

I'll make a PR for the xvfb, but LGTM is failing because this branch has merge conflicts with master. That can't be corrected.

> Also: did you have another PR for review today? Wonder if I accidentally deleted some notification.

No, no other PR from me.

**Comment by holgerd77** [comment]
Ok, I have now fetched the branch locally, run the tests locally (which passed) and then published to npm as [v2.2.1](https://github.com/ethereumjs/ethereumjs-block/releases/tag/v2.2.1) and also created the tagged version on that branch. I would now close this PR.

**Pull request closed without merging**
