### PR TITLE
Fix browserify issue

### PR DESCRIPTION
**Pull request by holgerd77**
Adresses #39

### CODE REVIEW

**Comment by axic** [comment]
I don't know enough about babel and karma to review this.

**Comment by holgerd77** [comment]
@axic Ok, also requested reviews from @Silur and/or @fanatid.

**Comment by mitra42** [comment]
Would be great to get this merged, its blocking updates on packages that depend on ethereumjs - even indirectly (like IPFS)

**Comment by holgerd77** [comment]
Will merge without review since I don't find a reviewer and PR is urgent.

**Comment by alanshaw** [comment]
Any chance this change can be made to `ethereumjs-util` as well?

**Comment by holgerd77** [comment]
@alanshaw https://github.com/ethereumjs/ethereumjs-util/pull/119

**Comment by holgerd77** [comment]
@alanshaw Could you please review this?

**Pull request merged**
