### PR TITLE
Export BlockHeader through Block.Header

### PR DESCRIPTION
**Pull request by fanatid**

### CODE REVIEW

**Comment by wanderer** [comment]
thanks @fanatid !

**Comment by fanatid** [comment]
@wanderer can you publish new version?

**Comment by wanderer** [comment]
@fanatid just a sec, im trying to see why the browser tests fail

**Comment by fanatid** [comment]
Looks like some of dependencies uses `let` in code, but by default travis uses Firefox 31...
`let` is supported only from firefox 44 [mdn](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/let)
try bump firefox version in [travis config](https://docs.travis-ci.com/user/firefox/)

**Comment by wanderer** [comment]
version 1.3.0 is now up

**Comment by fanatid** [comment]
@wanderer thank you!

**Pull request merged**
