### PR TITLE
Replace uses of deprecated `new Buffer` with Buffer.from

### PR DESCRIPTION
**Pull request by whymarrh**
See also https://github.com/ethereumjs/ethereumjs-blockchain/pull/80

This PR removes usages of the deprecated `new Buffer` API.

### CODE REVIEW

**Comment by holgerd77** [comment]
This should not be needed any more since we have dropped Node 4 (and 5) support with EOL being reached.

**Comment by axic** [comment]
Didn't know that. Does it make sense removing that workaround from the codebase then?

**Comment by whymarrh** [comment]
@axic yup, `safe-buffer` isn't needed and can be removed

**Comment by holgerd77** [comment]
Have opened a PR https://github.com/ethereumjs/organization/pull/45 to add a note on this to the docs, together with an additional table on Node.js distribution version support, @whymarrh can you directly do a review on this?

**Pull request merged**
