### PR TITLE
[Constantinople] Added difficulty bomb delay (EIP1234)

### LINKED ISSUE #53: [Constantinople] EIP 1234 Difficulty bomb delay and block reward adjustment
[EIP 1234](https://eips.ethereum.org/EIPS/eip-1234) Constantinople difficulty bomb delay and block reward adjustment (difficulty part in ``ethereumjs-block``, see [Byzantium PR](https://github.com/ethereumjs/ethereumjs-block/pull/32) for reference)

See e.g. [code here](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opFns.js#L161) in the VM on how to do HF switches, HF support/``_common`` instance is already added to this library.

### PR DESCRIPTION
**Pull request by alextsg**
Fixes #53

### CODE REVIEW

**Comment by alextsg** [comment]
@holgerd77 I'm not sure what's the best way to add tests here, as I don't think `difficultyConstantinople.json` exists yet on `ethereum/tests`.

**Comment by holgerd77** [comment]
Hmm, not sure, have asked here: https://github.com/ethereum/tests/issues/318

There is also [this](https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit#gid=1197466216) spreadsheet with the state of tests, difficulty section seems to be outdated though.

**Comment by alextsg** [comment]
Thanks @holgerd77. It sounds like tests are coming soon so I'll keep a lookout for that.

**Comment by holgerd77** [comment]
Difficulty tests for Constantinople are now merged, see new [difficultyConstantinople.json](https://github.com/ethereum/tests/blob/develop/BasicTests/difficultyConstantinople.json) file over on the ``ethereum/tests`` repo, so we can use this now for testing here in the library.

**Comment by holgerd77** [comment]
Hi @alextsg, I've now also released a new version [v0.6.0](https://github.com/ethereumjs/ethereumjs-common/releases/tag/v0.6.0) of the ``ethereumjs-common`` library including the miner reward parameter changes PR.

**Comment by alextsg** [comment]
Great, thanks @holgerd77! Will finish this up soon.

**Comment by holgerd77** [comment]
Hi Alex, if you could update here would be great, then we could finish this part up! 😃

**Comment by alextsg** [comment]
Sorry about that! Updated

**Pull request merged**
