### PR TITLE
v2.2.2 Release: Backports MuirGlacier difficulty adjustments

### PR DESCRIPTION
**Pull request by holgerd77**
[DO NOT MERGE THIS PR!!!]

Backport release analog to https://github.com/ethereumjs/ethereumjs-block/pull/77. This is branched off the `release/v2.2.1` branch, to be released as described [here](https://github.com/ethereumjs/ethereumjs-block/pull/87#issuecomment-565790390).

- [x] TravisCI runs through
- [x] Confirmation that browser tests run locally
- [x] Reviewed and approved
- [x] Publish npm release from local branch
- [x] Create GitHub release with `release/v2.2.2` as a target branch
- [x] Do not merge but close this PR, do not delete the branch

Open for review.

### CODE REVIEW

**Comment by holgerd77** [comment]
Ok, a bit annoying to do this old/already outdated work, but I also fixed the Travis xvfb issue analog to https://github.com/ethereumjs/ethereumjs-util/pull/221 to get at least the Node tests passing here.

This is done, now finally ready for review so that we can release (and subsequently do a blockchain and then the VM release on MuirGlacier).

**Comment by evertonfraga** [comment]
thanks for putting it together. i was planning to do it tonight.

**Comment by holgerd77** [comment]
No prob, let me know if you can approve.

**Comment by evertonfraga** [comment]
i assume ill need to approve again after the conflicts get solved. i can help with that if you want.

**Comment by holgerd77** [comment]
@evertonfraga Ah no, conflict solving is not necessary here since this won't get merged. This is just because the PR is opened against `master`.

**Comment by holgerd77** [comment]
Just released as [v2.2.2](https://github.com/ethereumjs/ethereumjs-block/releases/tag/v2.2.2) on npm.

**Comment by holgerd77** [comment]
@evertonfraga if you want you can already prepare a release on the blockchain library with an update on the block dependency + release notes (including the PRs merged since the last release).

**Comment by evertonfraga** [comment]
👍🏼

**Pull request closed without merging**
