### PR TITLE
Implementation of block difficulty adjustment for Metro-Byzantium (EIP100)

### PR DESCRIPTION
**Pull request by holgerd77**
Not ready for merging yet, not tested, just open for discussion

### CODE REVIEW

**Comment by axic** [comment]
Can you split the non-metropolis changes into a separate PR?

**Comment by holgerd77** [comment]
Hmm, this is all (somehow) related to Metropolis, which parts do you want to have split out?
(changelog, some test notes, Homestead method removal, difficulty adjustment)

**Comment by holgerd77** [comment]
(quick answer appreciated, then I can do this after lunch break :-))

**Comment by axic** [comment]
The first 3 commits if removing the metropolis changes from them.

**Pull request closed without merging**
